<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Emergencia.Consumer-03261c9f-7ff4-41e3-b29f-de19c4309ff6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CentrodeEmergencia.Shared\CentrodeEmergencia.Shared.csproj" />
    <ProjectReference Include="..\Emergencia.Infraestructura\Emergencia.Infraestructura.csproj" />
  </ItemGroup>
</Project>
